name: Deploy React Vite App

on:
  push:
    branches: ["main"]


jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setuo Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to GitHub Pages
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .dist
          
